/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************/
 /*******************************************************************************
                             Includes
*******************************************************************************/
#include"STM32F103C6_EXTERNALINTERRUPTS.h"


 /*******************************************************************************
                     INLINE FUNCTIONS DEFINITION
*******************************************************************************/
static inline void ACCESS_LEVEL_SWITCH_TO_UNPRIVILEGED(void){
	__asm("nop\n\tnop\n\tnop\n\t");
	__asm("MRS r0,CONTROL \n\t"
		  "ORR r0,r0,#0x1 \n\t"
		  "MSR CONTROL,r0");
	__asm("nop\n\tnop\n\tnop\n\t");
}

static inline void ACCESS_LEVEL_SWITCH_TO_PRIVILEGED(void){
	__asm("nop\n\tnop\n\tnop\n\t");
	__asm("MRS r0,CONTROL \n\t"
		  "LSR r0,r0,#0x1 \n\t"
		  "LSL r0,r0,#0x1 \n\t"
		  "MSR CONTROL,r0");
	__asm("nop\n\tnop\n\tnop\n\t");
}


/*******************************************************************************
                          IRQ HANDLERS
*******************************************************************************/
void ExternalInterruptRequest9CallBackFunction(void){
	ACCESS_LEVEL_SWITCH_TO_PRIVILEGED();
}


/*******************************************************************************
                          MAIN APPICATION
*******************************************************************************/
int main(void)
{
	/***********************************
	 *     Configuration of Clock     *
	 ***********************************/
	MCAL_RCC_PERIPHERAL_EN(RCC_GPIOB);
	MCAL_RCC_PERIPHERAL_EN(RCC_AFIO);


	/************************************************
	 *     Configuration of External Interrupts     *
	 ************************************************/
	EXTI_PinConfig_t ExternalInterruptConfiguration;
	ExternalInterruptConfiguration.EXTI_Pin = EXTI9PB9;
	ExternalInterruptConfiguration.IRQ_EN = EXTI_IRQ_ENABLE;
	ExternalInterruptConfiguration.Trigger_case = EXTI_Trigger_RISING;
	ExternalInterruptConfiguration.P_IRQ_CallBack = ExternalInterruptRequest9CallBackFunction;
	MCAL_EXTI_Init(&ExternalInterruptConfiguration);

	/***************************************************
	 *    SWITCHING FROM PRIVILEGED TO UNPRIVILEGED   *
	 **************************************************/
	ACCESS_LEVEL_SWITCH_TO_UNPRIVILEGED();
	while(1);
}
