/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include"STM32F103C6_GPIO.h"
void CLOCK_INIT(void){
	//Init clock for GPIO Port A
	RCC_GPIOA_CLOCK_EN();
	//Init clock for GPIO PORT B
	RCC_GPIOB_CLOCK_EN();

}
void GPIO_INIT(void){
	GPIO_PinConfig_t inputConfiguration;
	GPIO_PinConfig_t outputConfiguration;
	//Init PORTA1 as Floating Input
	inputConfiguration.GPIO_PinNumber = GPIO_PIN_1;
	inputConfiguration.GPIO_OutputSpeed = GPIO_SPEED_Input;
	inputConfiguration.GPIO_Mode = GPIO_MODE_Input_FLO;
	MCAL_GPIO_Init(GPIOA, &inputConfiguration);
	//Init PORTA13 as Floating Input
	inputConfiguration.GPIO_PinNumber = GPIO_PIN_13;
	inputConfiguration.GPIO_OutputSpeed = GPIO_SPEED_Input;
	inputConfiguration.GPIO_Mode = GPIO_MODE_Input_FLO;
	MCAL_GPIO_Init(GPIOA, &inputConfiguration);
	//Init PORTB1 as Push-Pull Output
	outputConfiguration.GPIO_PinNumber = GPIO_PIN_1;
	outputConfiguration.GPIO_OutputSpeed = GPIO_SPEED_10MHZ;
	outputConfiguration.GPIO_Mode = GPIO_MODE_Output_pp;
	MCAL_GPIO_Init(GPIOB, &outputConfiguration);
	//Init PORTB13 as Push-Pull Output
	//GPIOB_CRH |=(0b01<<20);
	//GPIOB_CRH &=~(0b11<<22);
	//Init PORTB1 as Push-Pull Output
	outputConfiguration.GPIO_PinNumber = GPIO_PIN_13;
	outputConfiguration.GPIO_OutputSpeed = GPIO_SPEED_10MHZ;
	outputConfiguration.GPIO_Mode = GPIO_MODE_Output_pp;
	MCAL_GPIO_Init(GPIOB, &outputConfiguration);

}

void delay(void){
	for (int i = 0 ; i<255;i++)
		for(int j = 0 ; j<255 ; j++);

}
int main(void)
{
	CLOCK_INIT();
	GPIO_INIT();

	while(1){
			/* Read PA1 */
			if(!(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1))){
				/* Single press */
				MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
				while(!(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1)));
				delay();
			}
			/* Read PA2 */
			if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13)){
				/* Multi press */
				MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
				delay();
			}
		}
}
