/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************/
 /*******************************************************************************
                             Includes
*******************************************************************************/
#include"STM32F103C6_EXTERNALINTERRUPTS.h"


 /*******************************************************************************
                   CONFIGURATION MACROS & EXTERN VARIABLES
*******************************************************************************/
#define TaskA_StackSize 	100
#define TaskB_StackSize 	100
#define MainStack_StackSize 512
#define Task_StackMargin 	8
extern uint32_t _estack;

 /*******************************************************************************
                          GLOBAL VARIABLES
*******************************************************************************/
uint32_t _S_MSP =(uint32_t) &_estack;
uint32_t _E_MSP;
uint32_t _S_PSP_TaskA;
uint32_t _E_PSP_TaskA;
uint32_t _S_PSP_TaskB;
uint32_t _E_PSP_TaskB;
uint8_t  InterruptRequestFlag;
uint8_t  TaskAFlag;
uint8_t  TaskBFlag;

/*******************************************************************************
                     INLINE FUNCTIONS PROTOTYPES
*******************************************************************************/
static inline void OS_SWITCH_ACCESS_LEVEL_TO_UNPRIVILEGED(void)__attribute__((always_inline));
static inline void OS_SWITCH_ACCESS_LEVEL_TO_PRIVILEGED(void)__attribute__((always_inline));
static inline void OS_SET_PSP(uint32_t address)__attribute__((always_inline));
static inline void OS_SWITCH_SP_SHADOW_PSP(void)__attribute__((always_inline));
static inline void OS_SWITCH_SP_SHADOW_MSP(void)__attribute__((always_inline));
static inline void OS_GENERATE_EXCEPTION(void)__attribute__((always_inline));
 /*******************************************************************************
                     INLINE FUNCTIONS DEFINITION
*******************************************************************************/
static inline void OS_SWITCH_ACCESS_LEVEL_TO_UNPRIVILEGED(void){
	__asm("MRS r0,CONTROL \n\t"
		  "ORR r0,r0,#0x1 \n\t"
		  "MSR CONTROL,r0");
}

static inline void OS_SWITCH_ACCESS_LEVEL_TO_PRIVILEGED(void){
	__asm("MRS r0,CONTROL \n\t"
		  "LSR r0,r0,#0x1 \n\t"
		  "LSL r0,r0,#0x1 \n\t"
		  "MSR CONTROL,r0");
}

static inline void OS_SET_PSP(uint32_t address){
	__asm("MOV r0,%[input0] \n\t"
		  "MSR PSP,r0"
		  :
		  :[input0]"r"(address));
}

static inline void OS_SWITCH_SP_SHADOW_PSP(void){
	__asm("MRS r0,CONTROL \n\t"
		  "MOV r1,#0x2    \n\t"
		  "ORR r0,r0,r1   \n\t"
		  "MSR CONTROL,r0");
}

static inline void OS_SWITCH_SP_SHADOW_MSP(void){
	__asm("MRS r0,CONTROL \n\t"
		  "MOV r1,#0x5    \n\t"
		  "AND r0,r0,r1   \n\t"
		  "MSR CONTROL,r0");
}

static inline void OS_GENERATE_EXCEPTION(void){
	__asm("SVC #0x3");
}
/*******************************************************************************
                          IRQ HANDLERS
*******************************************************************************/
void ExternalInterruptRequest9CallBackFunction(void){
	if(InterruptRequestFlag == 0){
		TaskAFlag = 1;
		TaskBFlag = 0;
		InterruptRequestFlag = 1;
	}else if(InterruptRequestFlag == 1){
		TaskBFlag = 1;
		TaskAFlag = 0;
		InterruptRequestFlag = 0;
	}
}

void SVC_Handler(void){
	OS_SWITCH_ACCESS_LEVEL_TO_PRIVILEGED();
}

/*******************************************************************************
                          MAIN APPICATION
*******************************************************************************/
int TaskA (int a, int b, int c){
	return a+b+c;
}
int TaskB (int a, int b, int c){
	return a*b*c;
}
void OS_Scheduler(){

	// 01. Memory Layout Initialization
	_E_MSP 			= (_S_MSP - MainStack_StackSize);
	_S_PSP_TaskA 	= (_E_MSP - Task_StackMargin);
	_E_PSP_TaskA 	= (_S_PSP_TaskA - TaskA_StackSize);
	_S_PSP_TaskB 	= (_E_PSP_TaskA - Task_StackMargin);
	_E_PSP_TaskB 	= (_S_PSP_TaskB - TaskB_StackSize);

	// 02. Scheduling Algorithm
	while(1){
		__asm("nop");
		if(TaskAFlag == 1){
			//2.1. Set the PSP register to point to the task A process stack top
			OS_SET_PSP(_S_PSP_TaskA);
			//2.2. Switch the SP to shadow the PSP instead of the MSP
			OS_SWITCH_SP_SHADOW_PSP();
			//2.3. Switch the access level from privileged to unprivileged
			OS_SWITCH_ACCESS_LEVEL_TO_UNPRIVILEGED();
			//2.4. Call the Task to Execute
			TaskA(1,2,3);
			//2.3. Switch the access level from unprivileged to privileged
			OS_GENERATE_EXCEPTION();
			//2.2. Switch the SP to shadow the MSP instead of the PSP
			OS_SWITCH_SP_SHADOW_MSP();
		}else if (TaskBFlag == 1){
			//2.1. Set the PSP register to point to the task A process stack top
			OS_SET_PSP(_S_PSP_TaskB);
			//2.2. Switch the SP to shadow the PSP instead of the MSP
			OS_SWITCH_SP_SHADOW_PSP();
			//2.3. Switch the access level from privileged to unprivileged
			OS_SWITCH_ACCESS_LEVEL_TO_UNPRIVILEGED();
			//2.4. Call the Task to Execute
			TaskB(1,2,3);
			//2.3. Switch the access level from unprivileged to privileged
			OS_GENERATE_EXCEPTION();
			//2.2. Switch the SP to shadow the MSP instead of the PSP
			OS_SWITCH_SP_SHADOW_MSP();
		}
	}
}
int main(void)
{
	/***********************************
	 *     Configuration of Clock     *
	 ***********************************/
	MCAL_RCC_PERIPHERAL_EN(RCC_GPIOB);
	MCAL_RCC_PERIPHERAL_EN(RCC_AFIO);


	/************************************************
	 *     Configuration of External Interrupts     *
	 ************************************************/
	EXTI_PinConfig_t ExternalInterruptConfiguration;
	ExternalInterruptConfiguration.EXTI_Pin = EXTI9PB9;
	ExternalInterruptConfiguration.IRQ_EN = EXTI_IRQ_ENABLE;
	ExternalInterruptConfiguration.Trigger_case = EXTI_Trigger_RISING;
	ExternalInterruptConfiguration.P_IRQ_CallBack = ExternalInterruptRequest9CallBackFunction;
	MCAL_EXTI_Init(&ExternalInterruptConfiguration);

	/***************************************************
	 *            CALLING THE OS SCHEDULER             *
	 **************************************************/
	OS_Scheduler();
	while(1);
}
