/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

/***********************
 * REGISTER ADDRESSES  *
 * *********************/

//GPIO REGISTERS
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_CRL *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_IDR *(volatile uint32_t *)(GPIOA_BASE + 0x08)
#define GPIOB_BASE 0x40010C00
#define GPIOB_CRH *(volatile uint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_CRL *(volatile uint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_ODR *(volatile uint32_t *)(GPIOB_BASE + 0x0C)
#define GPIOB_IDR *(volatile uint32_t *)(GPIOB_BASE + 0x08)


//CLOCKS REGISTERS
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR *(volatile uint32_t *)(RCC_BASE + 0x04)
#define RCC_CR *(volatile uint32_t *)(RCC_BASE + 0x00)


void CLOCK_INIT(void){
	//Init clock for GPIO Port A
	RCC_APB2ENR |= (0b1<<2);
	//Init clock for GPIO PORT B
	RCC_APB2ENR |= (0b1<<3);

}
void GPIO_INIT(void){

	//Init PORTA1 as Floating Input
	GPIOA_CRL |= (0b0100<<4);
	//Init PORTA13 as Floating Input
	GPIOA_CRH |= (0b0100<<20);
	//Init PORTB1 as Push-Pull Output
	GPIOB_CRL |=(0b01<<4);
	GPIOB_CRL &=~(0b11<<6);
	//Init PORTB13 as Push-Pull Output
	GPIOB_CRH |=(0b01<<20);
	GPIOB_CRH &=~(0b11<<22);

}

void delay(void){
	for (int i = 0 ; i<255;i++)
		for(int j = 0 ; j<255 ; j++);

}
int main(void)
{
	CLOCK_INIT();
	GPIO_INIT();

	while(1){
			/* Read PA1 */
			if(((GPIOA_IDR&(1<<1))>>1)==0){
				/* Single press */
				GPIOB_ODR ^= 1<<1;
				while((((GPIOA_IDR&(1<<1))>>1)==0));
			}
			/* Read PA2 */
			if(((GPIOA_IDR&(1<<13))>>1)){
				/* Multi press */
				GPIOB_ODR ^= 1<<13;
			}
			delay();
		}
}

