/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

// register address
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)

#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR *(volatile uint32_t *)(RCC_BASE + 0x04)
#define RCC_CR *(volatile uint32_t *)(RCC_BASE + 0x00)


int main(void)
{
	// Use only internal HSI_RC, Done by Default
	// SysClk 32 MHZ, PLL Multiplier by 4
	RCC_CFGR |=  (0b0110<<18);
	// Enable PLL
	RCC_CR |= (0b1<<24);
	// Control the SW Mux to select PLL Clk Source as SysClk
	RCC_CFGR |= (0b10);
	// AHB frequency 32 MHZ, Done by default as now SysClk is 32 and AHB prescaler equals 1

	//APB1 Bus frequency 16 MHZ
	RCC_CFGR &= ~(0b000<<8);
	RCC_CFGR |=  (0b100<<8);
	//APB2 Bus frequency 8 MHZ
	RCC_CFGR &= ~(0b000<<11);
	RCC_CFGR |=  (0b101<<11);


	//Init clock for GPIO Port A
	RCC_APB2ENR |= (1<<2);
	//Init GPIOA
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;

	while(1)
	{
		GPIOA_ODR |= 1<<13 ;
		for (int i = 0; i < 5000; i++); // arbitrary delay
		GPIOA_ODR &= ~(1<<13) ;
		for (int i = 0; i < 5000; i++); // arbitrary delay
	}
}

