/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************/
 /*******************************************************************************
                             Includes
*******************************************************************************/
#include"STM32F103C6_UART.h"
#include"STM32F103C6_SPI.h"
#define MCU_SPI_MASTER_MODE


/*******************************************************************************
                          Global Variables
*******************************************************************************/
extern uint16_t SPI_GPIO_Pins[2][4];
uint16_t data;


/*******************************************************************************
                          IRQ HANDLERS
*******************************************************************************/
void USART1_ReceiveInterruptCallBackFunction(void){
#ifdef MCU_SPI_MASTER_MODE
	MCAL_UART_ReceiveData(USART1, &data, UART_InterruptMechanism);
	MCAL_UART_SendData(USART1, &data, UART_PollingMechanism);

	//Force the slave select to the Busy Mode (LOW)
	MCAL_GPIO_WritePin(GPIOA, SPI_GPIO_Pins[SPI1_Index][SPIx_NSS_Index], LOW);
	MCAL_SPI_Send_Data(SPI1, &data, SPI_PollingMechanism);
	//Force the slave select to the Idle Mode (HIGH)
	//MCAL_GPIO_WritePin(GPIOA, SPI_GPIO_Pins[SPI1_Index][SPIx_NSS_Index], HIGH);
#endif
}


/*******************************************************************************
                          MAIN APPICATION
*******************************************************************************/
int main(void)
{
	/***********************************
	 *     Configuration of USART1     *
	 ***********************************/
	UART_Configuration_t UART1_Configuration;
	UART1_Configuration.BaudRate          = UART_BaudRate_115200;
	UART1_Configuration.HWFlowControl     = UART_HW_FlowControl_NONE;
	UART1_Configuration.IRQEnable         = UART_IRQ_Enable_RXNEIE;
	UART1_Configuration.P_IRQ_CallBack    = USART1_ReceiveInterruptCallBackFunction;
	UART1_Configuration.Parity            = UART_Parity_Disable;
	UART1_Configuration.PayloadLength     = UART_Payload_Length_8B;
	UART1_Configuration.NumberOfStopBits  = UART_StopBits_1;
	UART1_Configuration.Mode     		  = UART_Mode_BothTxRx;

	MCAL_UART_Init(USART1, &UART1_Configuration);
	MCAL_UART_GPIO_Set_Pins(USART1);


	/***********************************
	 *      Configuration of SPI1      *
	 ***********************************/
	SPI_Configuration_t SPI1_Configuration;

	SPI1_Configuration.CLKPhase 		 = SPI_CLK_PHASE_SECOND;
	SPI1_Configuration.CLKPolarity 		 = SPI_CLK_POLARITY_IDLE_HIGH;
	SPI1_Configuration.FrameSize 		 = SPI_FRAME_SIZE_8BIT;
	SPI1_Configuration.FrameFormat 		 = SPI_FRAME_FORMAT_MSB_FIRST;
	SPI1_Configuration.BaudRatePrescaler = SPI_BAUDERATE_PRESCALER_8;
	SPI1_Configuration.CommunicationMode = SPI_COMMUNICATION_MODE_2LINE_FULL_DUPLEX;

#ifdef MCU_SPI_MASTER_MODE
	SPI1_Configuration.Mode 				 = SPI_MODE_MASTER;
	SPI1_Configuration.IRQEnable 			 = SPI_IRQ_ENABLE_NONE;
	SPI1_Configuration.P_IRQ_CallBack 		 = NULL;
	SPI1_Configuration.SlaveSelectManagement = SPI_NSS_SW_SSI_SET;

	GPIO_PinConfig_t pinConfiguration;
	pinConfiguration.GPIO_PinNumber 	= SPI_GPIO_Pins[SPI1_Index][SPIx_NSS_Index];
	pinConfiguration.GPIO_OutputSpeed 	= GPIO_SPEED_10MHz;
	pinConfiguration.GPIO_Mode 			= GPIO_MODE_Output_PP;
	MCAL_GPIO_Init(GPIOA, &pinConfiguration);
#endif

	MCAL_SPI_Init(SPI1, &SPI1_Configuration);
	MCAL_SPI_GPIO_Set_Pins(SPI1);

	//Force the slave select to the Idle Mode (HIGH)
	MCAL_GPIO_WritePin(GPIOA, SPI_GPIO_Pins[SPI1_Index][SPIx_NSS_Index], HIGH);
	while(1);
}
