/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************/
 /*******************************************************************************
                             Includes
*******************************************************************************/
#include"STM32F103C6_EXTERNALINTERRUPTS.h"


/*******************************************************************************
                          IRQ HANDLERS
*******************************************************************************/
void ExternalInterruptRequest9CallBackFunction(void){
	MCAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, LOW);
}


/*******************************************************************************
                          MAIN APPICATION
*******************************************************************************/
int main(void)
{
	/***********************************
	 *     Configuration of Clock     *
	 ***********************************/
	MCAL_RCC_PERIPHERAL_EN(RCC_GPIOB);
	MCAL_RCC_PERIPHERAL_EN(RCC_AFIO);


	/************************************************
	 *     Configuration of External Interrupts     *
	 ************************************************/
	EXTI_PinConfig_t ExternalInterruptConfiguration;
	ExternalInterruptConfiguration.EXTI_Pin = EXTI9PB9;
	ExternalInterruptConfiguration.IRQ_EN = EXTI_IRQ_ENABLE;
	ExternalInterruptConfiguration.Trigger_case = EXTI_Trigger_RISING;
	ExternalInterruptConfiguration.P_IRQ_CallBack = ExternalInterruptRequest9CallBackFunction;
	MCAL_EXTI_Init(&ExternalInterruptConfiguration);


	while(1);
}
