/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************/
 /*******************************************************************************
                             Includes
*******************************************************************************/
#include <stdint.h>
#include "../CMSIS_Version5/core_cm3.h"


/*******************************************************************************
                   CONFIGURATION MACROS & EXTERN VARIABLES
*******************************************************************************/
#define SVC_ADDITION_OPERATION 			0
#define SVC_SUBSTRACTION_OPERATION 		1
#define SVC_MULTPLICATION_OPERATION 	2
#define SVC_PendSV_REQUEST				3



/*******************************************************************************
                          GLOBAL VARIABLES
*******************************************************************************/
uint8_t AdditionResult;
uint8_t SubstractionResult;
uint8_t MultplicationResult;


/*******************************************************************************
                     INTERNALLY USED FUNCTIONS DEFINITION
*******************************************************************************/
void OS_SVC_SERVICEPROVIDER (uint32_t* CallerStackFramePointer){
	uint8_t SVC_Number;
	uint8_t Argument1, Argument2;
	Argument1 = CallerStackFramePointer[0];
	Argument2 = CallerStackFramePointer[1];
	SVC_Number = *((uint8_t*)((uint8_t*)(CallerStackFramePointer[6])-2));
	switch(SVC_Number){
	case(SVC_ADDITION_OPERATION):
			CallerStackFramePointer[0] = Argument1 + Argument2;
			break;
	case(SVC_SUBSTRACTION_OPERATION):
			CallerStackFramePointer[0] = Argument1 - Argument2;
			break;
	case(SVC_MULTPLICATION_OPERATION):
			CallerStackFramePointer[0] = Argument1 * Argument2;
			break;
	case(SVC_PendSV_REQUEST):
			SCB->ICSR |= SCB_ICSR_PENDSVSET_Msk;
			break;
	}
}


/*******************************************************************************
                          IRQ HANDLERS
*******************************************************************************/
void PendSV_Handler(){
	SCB->ICSR |= SCB_ICSR_PENDSVCLR_Msk;
}
__attribute ((naked)) void SVC_Handler (){
	__asm("TST   LR, #4   \n\t"
		  "ITE   EQ 	  \n\t"
		  "MRSEQ R0,MSP   \n\t"
		  "MRSNE R0,PSP   \n\t"
		  "B 	 OS_SVC_SERVICEPROVIDER");
}


/*******************************************************************************
                          MAIN APPICATION
*******************************************************************************/
int OS_SVC_SERVICEREQUEST(uint32_t a, uint32_t b,uint32_t Operation){
	uint32_t returnValue;
	switch(Operation){
	case SVC_ADDITION_OPERATION:
		__asm("SVC #0x00");
		break;
	case SVC_SUBSTRACTION_OPERATION:
		__asm("SVC #0x01");
		break;
	case SVC_MULTPLICATION_OPERATION:
		__asm("SVC #0x02");
		break;
	case SVC_PendSV_REQUEST:
		__asm("SVC #0x03");
		break;
	}
	__asm("MOV %[output0],r0"
		 :[output0] "=r" (returnValue));
	return returnValue;
}
int main(void)
{

	/****************************************************
	 *      CALLING THE OS SVC SERVICE REQUESTS         *
	 ****************************************************/
	AdditionResult = OS_SVC_SERVICEREQUEST(5, 5, SVC_ADDITION_OPERATION);
	SubstractionResult = OS_SVC_SERVICEREQUEST(5, 5, SVC_SUBSTRACTION_OPERATION);
	MultplicationResult = OS_SVC_SERVICEREQUEST(5, 5, SVC_MULTPLICATION_OPERATION);

	OS_SVC_SERVICEREQUEST(0, 0, SVC_PendSV_REQUEST);

	while(1);
}
