/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************/
 /*******************************************************************************
                             Includes
*******************************************************************************/
#include"STM32F103C6_EXTERNALINTERRUPTS.h"


 /*******************************************************************************
                          GLOBAL VARIABLES
*******************************************************************************/
uint8_t variableToReadCONTROLRegValue;
uint8_t variableToReadIPSRRegValue;

/*******************************************************************************
                          IRQ HANDLERS
*******************************************************************************/
void ExternalInterruptRequest9CallBackFunction(void){
	__asm("nop\n\t nop\n\t nop\n\t");

	__asm("MRS %[output0],IPSR"
		   :[output0] "=r"(variableToReadIPSRRegValue));

	__asm("nop\n\t nop\n\t nop\n\t");
}


/*******************************************************************************
                          MAIN APPICATION
*******************************************************************************/
int main(void)
{
	/***********************************
	 *     Configuration of Clock     *
	 ***********************************/
	MCAL_RCC_PERIPHERAL_EN(RCC_GPIOB);
	MCAL_RCC_PERIPHERAL_EN(RCC_AFIO);


	/************************************************
	 *     Configuration of External Interrupts     *
	 ************************************************/
	EXTI_PinConfig_t ExternalInterruptConfiguration;
	ExternalInterruptConfiguration.EXTI_Pin = EXTI9PB9;
	ExternalInterruptConfiguration.IRQ_EN = EXTI_IRQ_ENABLE;
	ExternalInterruptConfiguration.Trigger_case = EXTI_Trigger_RISING;
	ExternalInterruptConfiguration.P_IRQ_CallBack = ExternalInterruptRequest9CallBackFunction;
	MCAL_EXTI_Init(&ExternalInterruptConfiguration);

	/***************************************************
	 *    ASSEMBLY SECTION TO READ CONTROL REGISTER    *
	 **************************************************/
	__asm("nop\n\t nop\n\t nop\n\t");

	__asm("MRS %[output0],CONTROL"
		   :[output0] "=r"(variableToReadCONTROLRegValue));

	__asm("nop\n\t nop\n\t nop\n\t");
	while(1);
}
